# Generated by Django 5.0.7 on 2024-08-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_servings_time_unit_recipe_servings_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time',
            new_name='servings',
        ),
    ]
